language: go
services:
- docker
go:
- go1.13.x
script:
- make test
before_deploy:
- make debs
- export DEB_VERSION=$(git describe --tags --always | sed s/^v//)
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- make docker-push
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: "oRgJdZouAhHxSfwNSuI5fy6pCsvsCuPfvqzt6i11js77CFvtyLu3XlG8kWVKNeJGxPU+Lnu5Hn6xhSYD8zx+UqchgnPlxuzouzhefIyD9WIbsyQw3jSlZukqXPijjcDd3x3QbiBESyyG4TDK2N9YDAG00XJVt2A8p0dZ01cuDww="
  file: log-shuttle_${DEB_VERSION}_amd64.deb
  on:
    tags: true
    repo: heroku/log-shuttle
- provider: packagecloud
  skip_cleanup: true
  repository: open
  username: heroku
  token:
    secure: GcoejgkhMk8JC9KJQwKho0XDST2adk/7HzEM1+5CiftXgc+Y17+GLIBm4uKaVIqugkMPU5av3IbAMJkcyoSN9rpiPoYBbc/cCxoR8OCMYWASuD25+U75ptMTV692jLYr2VKa4wJ+vg1IIwsNJ5ypGuxLFpc7SOd4LylaBQ3S0go=
  dist: ubuntu/focal
  package_glob: "*.deb"
  on:
    tags: true
    repo: heroku/log-shuttle
- provider: packagecloud
  skip_cleanup: true
  repository: open
  username: heroku
  token:
    secure: GcoejgkhMk8JC9KJQwKho0XDST2adk/7HzEM1+5CiftXgc+Y17+GLIBm4uKaVIqugkMPU5av3IbAMJkcyoSN9rpiPoYBbc/cCxoR8OCMYWASuD25+U75ptMTV692jLYr2VKa4wJ+vg1IIwsNJ5ypGuxLFpc7SOd4LylaBQ3S0go=
  dist: ubuntu/trusty
  package_glob: "*.deb"
  on:
    tags: true
    repo: heroku/log-shuttle
env:
  global: #DOCKER_EMAIL, DOCKER_PASSWORD, DOCKER_USERNAME
  - secure: pNIDqDmqOWV3afbSY11QaIAdnsZyQ+/OA+gMLpeA44EPkj4yoTbDVBv8Y5sHlpPkP1fmPsfZKPNTbVXUnGPkJ4Y2dFVt8n5sJYtlV+pHzPf50JUmGNzxuxb9bWxKP5XM/ka3wujAibZMQdJDeMhP9Q0CSi8x5L/wQN+8hB56DhY=
  - secure: Ps5ZA+Tg6k3dwkGcabl+4ci47ARwzzQDKka/3TgnSBroHqvuF6yx0/XnDv3GNe9kUE402apAO4Kt1aEBSQ8DExwCdyCv8f8RzsiygjrkYEPiDbVPgIvmru6xMWAr/MPWv3xWQF1Yf1AzOtDvXOgRiFgGIBLMYVAPYMCgS8AuPFU=
  - secure: jOlEUnly5Kvats37qv9/p0YtqToYgehV4SI9qQ6YW+Zzzmz3rwkH/ht/pcDnTcUMYb67HXtmutOTs/NG0F23S6RwCgioc7GEaUW21OXUNkKorSmizPzDv36NH0nzJVrG2WRTzoKErsBoVieT2MxOtQrASEwMSHtJdfOD5NCIijo=
