language: go
services:
- docker
sudo: required
go:
- go1.9.3
script:
- make test
before_deploy:
- make debs
- export DEB_VERSION=$(git describe --tags --always | sed s/^v//)
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- make docker-push
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: XLs592eds4fC6/dqefrOC8w8lZIK1/Hj+u3EFW3HSdgFI/5lMNG+DaN9GLDKLdm8mYkAf+te6vdiai3e2jg48Tox17nGzia280WRn2mGUWx4HaDvKOPsprQCnMNz7mLeKokaP7YnwFhqd6bjWD6xpS53I6OSjbW9wM+V0sN21Vo=
    file: log-shuttle_${DEB_VERSION}_amd64.deb
    on:
      tags: true
      repo: heroku/log-shuttle
  - provider: packagecloud
    skip_cleanup: true
    repository: "open"
    username: "heroku"
    token:
      secure: "noS4YOfugFPsUEHezZ2ZS24hVfuTGRcO/j2o1jlR+F2eQc8jLViMf2tWOBBciZOIXmiHyYTpApQ/jA6wY8L/xwsLQWkzr14yv+/pJjfYCHlDNKhdA7/+OHycDaSFBavBGUYQlxY8MwdWjHsuBWcq2LZ8SQpod6y81DX16D9kppY="
    dist: ubuntu/trusty
    package_glob: *.deb
    on:
      tags: true
      repo: heroku/log-shuttle
env:
  global:
  - secure: PGlgN8iLUyf0+JgPS774jVms0RxlLvyF9mH0mofca/kGb2tgCrSkbZMFMPhBmcPISNP/RPKugrO6rrAGMvm+C04VC+NCfr32im5Al4Of0inhlwi6Xk015LfDYs6Oo8GHRMa4XSCnfhkIx+/xUO1w9JeE5vtVGEPTGcLnNbRZQ84=
  - secure: I6Yk2OKzgelw1mkwZyq5kUxt8UOfFM3TEf9Wa4NpInshmbP8fxUZEeD+gMAQOneuICiM0RwfOomikqGeEcYiery2/WDILZ5j4+0MqyKthoBqTDRHhVw/r9Y7hQ3gGiSq1s2CihiEL++Jkatxm9PaxxOxaYiFDvtk8ALCC4rc1AA=
  - secure: dTATw5SQCuegg8ZDvlOe+P0op4aE++CGKujKBJhCbbsvf6nU5m1ykb5DIM4Gbb+qD76rTaqafU2l75ag8hhBIeGDTgwSmNHgGbJU/HapI65UVaupmH5SY7kMnIsL5jbiAlLPWPaMABQFN588UVxcWF71CekD0zGVd6i5fAGYjA0=
